Repository COS301-SE-2023/AI-Photo-Editor, pull requests merged in 2023-09, with the labels that each got.

#143 Feature/keybindings
  .github/codecov.yml
  .github/workflows/coverage.yml
  src/electron/lib/api/apis/UtilApi.ts
  src/electron/utils/settings.ts
  src/frontend/ui/base/Settings.svelte
  src/frontend/ui/tiles/ShortcutSettings.svelte
  src/shared/types/setting.ts
  tests/unit-tests/electron/lib/ai/AiManager.spec.ts
Labels: scope: UI

#160 Refresh for plugins is working again
  src/electron/lib/plugins/Plugin.ts
  src/electron/lib/plugins/PluginManager.ts
  src/electron/lib/plugins/pluginCommands.ts
  src/electron/lib/registries/TypeclassRegistry.ts
Labels: type: bug

#159 keybindings are immediately in effect
  src/electron/lib/api/apis/UtilApi.ts
  src/frontend/lib/stores/BlixStore.ts
  src/frontend/lib/stores/ShortcutStore.ts
Labels: type: bug

#161 Refactor parts of undo/redo system
  package-lock.json
  package.json
  src/electron/lib/Blix.ts
  src/electron/lib/ai/AiLang.ts
  src/electron/lib/ai/AiManagerv2.ts
  src/electron/lib/api/apis/GraphApi.ts
  src/electron/lib/core-graph/CoreGraph.ts
  src/electron/lib/core-graph/CoreGraphEventManger.ts
  src/electron/lib/core-graph/CoreGraphManager.ts
  src/electron/lib/projects/ProjectCommands.ts
  src/electron/lib/projects/ProjectManager.ts
  src/frontend/lib/stores/GraphStore.ts
  src/frontend/ui/base/Splash.svelte
  src/frontend/ui/tiles/Graph.svelte
  src/frontend/ui/utils/graph/NodeUIComponent.svelte
  src/frontend/ui/utils/graph/NodeUIFragment.svelte
  src/frontend/ui/utils/graph/PluginNode.svelte
  src/frontend/ui/utils/graph/nodeUICcomponents/ColorPicker.svelte
  src/frontend/ui/utils/graph/nodeUICcomponents/Dropdown.svelte
  src/frontend/ui/utils/graph/nodeUICcomponents/Slider.svelte
  src/shared/types/graph.ts
Labels: scope: backend

#167 Fixed blank recent project, close #149
  src/electron/lib/projects/ProjectCommands.ts
Labels: type: bug

#170 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: scope: client, scope: admin

#182 Implement undo/redo system to work with text inputs
  src/frontend/lib/stores/GraphStore.ts
  src/frontend/lib/stores/MediaStore.ts
  src/frontend/ui/utils/graph/nodeUICcomponents/TextInput.svelte
Labels: type: fix, scope: UI

#185 Fix GLFX plugin and anchors
  blix-plugins/glfx-plugin/src/main.cjs
  blix-plugins/glfx-plugin/webview/App.svelte
  blix-plugins/threlte-plugin/src/main.cjs
Labels: scope: UI

#188 Fix interpreter bug
  src/electron/lib/core-graph/CoreGraphInterpreter.ts
Labels: scope: backend

#191 Add extra check for equivalence of media outputIds
  src/frontend/lib/stores/MediaStore.ts
Labels: scope: UI

#192 Fix/auto updates
  .github/workflows/build.yml
  electron-builder.yml
  package-lock.json
  package.json
  src/electron/lib/BlixCommands.ts
  src/electron/lib/api/apis/UtilApi.ts
  src/frontend/lib/api/apis/UtilClientApi.ts
  src/frontend/lib/stores/BlixStore.ts
  src/frontend/lib/stores/ShortcutStore.ts
  src/frontend/ui/base/App.svelte
  src/frontend/ui/base/settings/About.svelte
  src/frontend/ui/base/settings/AiSettings.svelte
  src/frontend/ui/base/settings/Hotkeys.svelte
  src/frontend/ui/base/settings/Settings.svelte
  src/frontend/ui/base/settings/utils/Button.svelte
  src/frontend/ui/base/settings/utils/Dropdown.svelte
  src/frontend/ui/base/settings/utils/SettingsItem.svelte
  src/index.ts
  src/shared/types/setting.ts
Labels: scope: ci/cd

#184 Fix layout switching bug when changing projects
  electron-builder.yml
  src/frontend/ui/base/ProjectBar.svelte
  src/frontend/ui/base/layout/Layout.svelte
  src/frontend/ui/base/layout/Panel.svelte
  src/frontend/ui/tiles/Graph.svelte
Labels: type: bug, type: fix, scope: UI

#193 Add/glfx nodes
  blix-plugins/glfx-plugin/src/main.cjs
  src/frontend/ui/tiles/WebView.svelte
Labels: scope: backend

#204 Refactor blink UI components to work with undo/redo system
  blix-plugins/input-plugin/src/main.js
  src/frontend/ui/utils/graph/nodeUIComponents/CachePicker.svelte
  src/frontend/ui/utils/graph/nodeUIComponents/ColorPicker.svelte
  src/frontend/ui/utils/graph/nodeUIComponents/Dropdown.svelte
  src/frontend/ui/utils/graph/nodeUIComponents/NumberInput.svelte
Labels: type: refactor, scope: UI

#202 Improve robustness of Blypescript Toolbox and Plugins
  blix-plugins/glfx-plugin/package.json
  blix-plugins/glfx-plugin/src/main.cjs
  blix-plugins/input-plugin/package.json
  blix-plugins/input-plugin/src/main.js
  blix-plugins/math-plugin/package.json
  src/electron/lib/Blix.ts
  src/electron/lib/ai/AiLang.ts
  src/electron/lib/ai/AiManagerv2.ts
  src/electron/lib/ai/ai-profiler-v2.ts
  src/electron/lib/ai/prompt.ts
  src/electron/lib/api/apis/UtilApi.ts
  src/frontend/ui/base/settings/utils/SettingsItem.svelte
  src/frontend/ui/tiles/Assets.svelte
  tests/unit-tests/electron/lib/ai/AiLang.spec.ts
Labels: type: fix, scope: backend

#203 Feature/export
  blix-plugins/blink/webview/App.svelte
  blix-plugins/glfx-plugin/src/main.cjs
  blix-plugins/glfx-plugin/webview/App.svelte
  blix-plugins/threlte-plugin/src/main.cjs
  src/electron/lib/cache/CacheManager.ts
  src/electron/lib/webviews/preload.ts
  src/frontend/lib/stores/CacheStore.ts
  src/frontend/ui/tiles/Assets.svelte
  src/frontend/ui/tiles/Media.svelte
  src/frontend/ui/tiles/WebView.svelte
  src/shared/types/cache.ts
Labels: scope: backend

#212 Feature/blink nodes
  blix-plugins/blink/src/main.cjs
  blix-plugins/blink/webview/types.ts
  src/electron/lib/core-graph/CoreGraphInterpreter.ts
Labels: scope: plugin

#214 Add CoreGraph manager tests
  tests/unit-tests/electron/lib/core-graph/CoreGraphEventManager.spec.ts
  tests/unit-tests/electron/lib/core-graph/CoreGraphManager.spec.ts
Labels: type: fix

#222 Refactor/projects
  .github/workflows/coverage.yml
  package-lock.json
  package.json
  src/electron/lib/Blix.ts
  src/electron/lib/api/apis/GraphApi.ts
  src/electron/lib/cache/CacheManager.ts
  src/electron/lib/core-graph/CoreGraphCommands.ts
  src/electron/lib/core-graph/CoreGraphManager.ts
  src/electron/lib/projects/ProjectCommands.ts
  src/electron/lib/webviews/preload.ts
  src/frontend/lib/api/apis/ProjectClientApi.ts
  src/frontend/lib/stores/CacheStore.ts
  src/frontend/lib/stores/GraphStore.ts
  src/frontend/lib/stores/MediaStore.ts
  src/frontend/lib/stores/ProjectStore.ts
  src/frontend/ui/base/ProjectBar.svelte
  src/frontend/ui/base/palette/Palette.svelte
  src/frontend/ui/tiles/Assets.svelte
  src/frontend/ui/tiles/Graph.svelte
  src/shared/types/cache.ts
  tests/integration-tests/plugins/plugin.spec.ts
  tests/integration-tests/projects/projectCommands.spec.ts
Labels: scope: backend
